import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Navbar from "./components/navbar";
import ClientOnly from "./components/client-only";
import RegisterModal from "./components/register-modal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "./components/login-modal";
import getCurrentUser from "./actions/getCurrentUser";
import RentModal from "./components/rent-modal";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <RentModal />
          <RegisterModal />
          <LoginModal />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        <div className="pb-20 pt-28 ">{children}</div>
      </body>
    </html>
  );
}
